version: 2.1

defaults: &defaults
  docker: 
    - image: jcuffney/node-ci-image:1.0.26
  working_directory: ~/repo

jobs:

  dependencies:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  lint: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint

  tests: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test

  publish_expo_dev: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npx expo login --non-interactive -u jcuffney
      - run: npx expo optimize --non-interactive --config app.dev.json
      - run: npx expo publish --non-interactive --config app.dev.json
      - run: npx expo logout --non-interactive

  publish_expo_prod: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npx expo login --non-interactive -u jcuffney
      - run: npx expo optimize --non-interactive --config app.prod.json
      - run: npx expo publish --non-interactive --config app.prod.json
      - run: npx expo logout --non-interactive
   
  publish_google_play: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npx expo login --non-interactive -u jcuffney
      - run: npx expo optimize --non-interactive --config app.prod.json
      - run: npx expo build:ios --non-interactive --config app.prod.json
      - run: npx expo logout --non-interactive

  publish_ios_app_store: 
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npx expo login --non-interactive -u jcuffney
      - run: npx expo optimize --non-interactive --config app.prod.json
      - run: npx expo build:ios --non-interactive --config app.prod.json
      - run: npx expo logout --non-interactive

workflows:
  version: 2
  publish:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - tests:
          requires:
            - dependencies
      - publish_expo_dev:
          context: EXPO
          requires:
            - dependencies
            - lint
            - tests
          filters:
            branches:
              only: dev
      - publish_expo_prod:
          context: EXPO
          requires:
            - dependencies
            - lint
            - tests
          filters:
            branches:
              only: master
      - publish_google_play:
          requires:
            - dependencies
            - lint
            - tests
          filters:
            branches:
              only: master
      - publish_ios_app_store:
          requires:
            - dependencies
            - lint
            - tests
          filters:
            branches:
              only: master